name: clippy

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - master

jobs:
  Lint:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type != 'tag' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Rust linting tools
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run full pedantic clippy lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --tests --workspace -- -Dclippy::all -Dclippy::pedantic -D warnings

  # Audit:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: EmbarkStudios/cargo-deny-action@v1


