name: Test

on:
  push:
    branches:
      - master
      - develop
    tags:
      - '*'
  # pull_request:
  #   branches:
  #     - master

env:
  RELEASE_COMMIT: ${{ github.ref_type == 'tag' }}
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  RUST_LOG: 'debug'


jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [1.56.0, stable]
        exclude:
          - os: ubuntu-latest
            rust: 1.56.0
          # - os: windows-latest
          #   rust: 1.56.0
          # - os: ubuntu-latest
          #   rust: nightly
          # - os: windows-latest
          #   rust: nightly

    runs-on: ${{ matrix.os }}
    # runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Build (${{ matrix.os }}-${{ matrix.rust }})
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Set RUST_TEST_{NOCAPTURE, THREADS}
        run: echo "RUST_TEST_NOCAPTURE=1" >> $GITHUB_ENV && echo "RUST_TEST_THREADS=1" >> $GITHUB_ENV
      - name: Run test suits in modules (${{ matrix.os }}-${{ matrix.rust }})
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features updater --lib
      - name: Run doc tests (${{ matrix.os }}-${{ matrix.rust }})
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features updater --doc
  Publish:
    runs-on: macos-latest
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Rust linting tools
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      # - name: Publish to crates.io
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: publish
      #     args: --all-features
      - name: Publish to crates.io
        run: CARGO_REGISTRY_TOKEN=${{ secrets.CARGO_REGISTRY_TOKEN }} cargo publish --all-features
